name = "maillage"
version = "1.0.0"

target = "javascript"

[javascript]
typescript_declarations = true

[lustre-dev.start]
proxy = { from = "/", to = "http://localhost:8080" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
lustre = ">= 4.6.3 and < 5.0.0"
lustre_ui = ">= 0.4.0 and < 1.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
lustre_http = ">= 0.6.0 and < 1.0.0"
# gleam_fetch = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
